name: gps-logger MAN

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Application version"
        required: true
        default: "v00.01.00"

jobs:
  build_arm_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.2.2
        with:
          context: ./build-context
          file: ./build-context/Dockerfile
          platforms: linux/arm/v7
          build-args: |
            RELEASE_TAG=${{ github.event.inputs.version }}
          push: true
          tags: |
            wagoautomation/gps-logger:testing